'use client';

import React, { useState, useEffect } from 'react';
import { useResearchStore } from '../store/useResearchStore';
import { HeroSection } from '../components/HeroSection';
import { ExecutiveSummary } from '../components/dashboard/ExecutiveSummary';
import { KeyInsights } from '../components/dashboard/KeyInsights';
import { TechnicalDeepDive } from '../components/dashboard/TechnicalDeepDive';
import { TrendAnalysis } from '../components/dashboard/TrendAnalysis';
import { OpportunitiesRisks } from '../components/dashboard/OpportunitiesRisks';
import { KnowledgeGraph } from '../components/dashboard/KnowledgeGraph';
import { SourceExplorer } from '../components/dashboard/SourceExplorer';
import { ImageGallery } from '../components/dashboard/ImageGallery';
import { ResearchCopilot } from '../components/dashboard/ResearchCopilot';
import { exportToJSON, exportToMarkdown, exportToWord } from '../utils/docExporter';
import { Card } from '../components/ui/Card';
import { ProgressRing } from '../components/ui/ProgressRing';
import { 
  Sparkles, History, HelpCircle, Download, FileText, Code, Database,
  ArrowLeft, Trash2, Check, RefreshCw, GitCompare, Landmark, MessageSquareCode
} from 'lucide-react';

export default function Home() {
  const { 
    isLoading, activeReport, history, loadingStage,
    startResearch, setActiveReport, deleteReport, getChangeDetection 
  } = useResearchStore();

  const [activeTab, setActiveTab] = useState<'summary' | 'insights' | 'technical' | 'graph' | 'sources' | 'risks' | 'timeline' | 'comparison'>('summary');
  const [showHistory, setShowHistory] = useState(false);
  const [showDiffModal, setShowDiffModal] = useState(false);
  const [copyStatus, setCopyStatus] = useState(false);

  // Auto-redirect active tab if comparison mode changes
  useEffect(() => {
    if (activeReport?.competitorComparison) {
      setActiveTab('comparison');
    } else {
      setActiveTab('summary');
    }
  }, [activeReport]);

  const pipelineStages = [
    "Expanding Query & Research Variants",
    "Connecting to Context.dev Search Index",
    "Scraping authoritative live URL Markdown",
    "Evaluating source authority metrics",
    "Running claim verification tests",
    "Locating contradictory evidence & risks",
    "Extracting source image assets",
    "Synthesizing Gemini multi-agent reports"
  ];

  const handleShare = () => {
    if (!activeReport) return;
    const shareText = `Check out this research report on ${activeReport.title} generated by NEXUS.`;
    navigator.clipboard.writeText(window.location.href);
    setCopyStatus(true);
    setTimeout(() => setCopyStatus(false), 2000);
  };

  const triggerPrintPDF = () => {
    window.print();
  };

  const diffData = getChangeDetection();

  return (
    <div className="min-h-screen flex flex-col relative">
      
      {/* 1. TOP NAVIGATION */}
      <nav className="border-b border-white/5 bg-slate-950/60 backdrop-blur-md px-6 py-4 flex items-center justify-between sticky top-0 z-30 no-print">
        <div className="flex items-center gap-3">
          <div className="w-8 h-8 rounded-xl bg-gradient-to-br from-purple-500 via-indigo-500 to-cyan-500 flex items-center justify-center shadow-lg shadow-purple-500/10">
            <Sparkles className="w-4 h-4 text-white animate-pulse" />
          </div>
          <span className="text-xl font-black tracking-tight text-white">NEXUS</span>
          <span className="text-[10px] uppercase font-bold tracking-widest text-slate-500 bg-white/5 border border-white/5 px-2 py-0.5 rounded-full">Research OS</span>
        </div>

        {/* Navigation Actions */}
        <div className="flex items-center gap-3">
          {history.length > 0 && (
            <div className="relative">
              <button 
                onClick={() => setShowHistory(!showHistory)}
                className="flex items-center gap-2 px-3 py-1.5 rounded-xl bg-white/5 hover:bg-white/10 border border-white/5 text-xs text-slate-300 hover:text-white transition-all font-semibold"
              >
                <History className="w-3.5 h-3.5" /> History ({history.length})
              </button>

              {/* History Dropdown Drawer */}
              {showHistory && (
                <div className="absolute right-0 mt-2 w-80 bg-slate-900 border border-white/10 rounded-2xl shadow-2xl p-4 space-y-3 z-50">
                  <h4 className="text-xs font-bold text-slate-400 uppercase tracking-wider">Research History</h4>
                  <div className="max-h-60 overflow-y-auto space-y-2">
                    {history.map((h) => (
                      <div 
                        key={h.id}
                        className={`flex items-center justify-between p-2 rounded-xl border text-left transition-all ${
                          activeReport?.id === h.id 
                            ? 'bg-purple-500/15 border-purple-500/30' 
                            : 'bg-slate-950/40 border-white/5 hover:border-white/10'
                        }`}
                      >
                        <button 
                          onClick={() => {
                            setActiveReport(h);
                            setShowHistory(false);
                          }}
                          className="flex-1 text-left"
                        >
                          <div className="text-xs font-bold text-slate-200 truncate pr-2">{h.title}</div>
                          <div className="text-[10px] text-slate-500 mt-0.5">{new Date(h.timestamp).toLocaleDateString()}</div>
                        </button>
                        <button 
                          onClick={() => deleteReport(h.id)}
                          className="p-1 hover:bg-rose-500/10 rounded text-slate-500 hover:text-rose-400 transition-colors"
                        >
                          <Trash2 className="w-3.5 h-3.5" />
                        </button>
                      </div>
                    ))}
                  </div>
                </div>
              )}
            </div>
          )}

          <a
            href="https://docs.context.dev"
            target="_blank"
            rel="noopener noreferrer"
            className="p-2 bg-slate-950/40 hover:bg-slate-900 border border-white/5 hover:border-white/10 text-slate-400 hover:text-white rounded-xl transition-all"
            title="API Documentation"
          >
            <HelpCircle className="w-4 h-4" />
          </a>
        </div>
      </nav>

      {/* 2. MAIN STATE ROUTER */}
      <main className="flex-1 flex flex-col p-6 max-w-[1400px] w-full mx-auto relative z-10">
        
        {/* Loading Pipeline View */}
        {isLoading && (
          <div className="flex-1 flex flex-col justify-center items-center py-12 space-y-8 animate-fade-in no-print">
            <div className="relative">
              <ProgressRing percentage={Math.round(((loadingStage + 1) / 8) * 100)} size={160} strokeWidth={12} label="Processing" />
              <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-20 h-20 rounded-full border border-purple-500/30 border-t-purple-500 animate-spin pointer-events-none" />
            </div>

            <div className="text-center space-y-4 max-w-md">
              <h3 className="text-lg font-bold text-slate-100 flex items-center justify-center gap-2">
                <RefreshCw className="w-4 h-4 animate-spin text-purple-400" /> Orchestrating Research Agents
              </h3>
              <p className="text-xs text-slate-500 leading-relaxed">
                Context.dev is fetching live sources and scanning parameters, which are then parsed and cross-checked by our verification nodes.
              </p>
            </div>

            {/* Stepper list */}
            <Card className="w-full max-w-md bg-slate-900/30 border-white/5 p-6 space-y-3 relative overflow-hidden">
              {pipelineStages.map((stage, idx) => {
                const isDone = loadingStage > idx;
                const isCurrent = loadingStage === idx;
                return (
                  <div 
                    key={idx}
                    className={`flex items-center gap-3 text-xs transition-all duration-300 ${
                      isDone ? 'text-emerald-400 font-medium' : isCurrent ? 'text-purple-300 font-bold' : 'text-slate-600'
                    }`}
                  >
                    <div className={`w-4 h-4 rounded-full border flex items-center justify-center shrink-0 ${
                      isDone 
                        ? 'bg-emerald-500/10 border-emerald-500/30 text-emerald-400' 
                        : isCurrent 
                        ? 'border-purple-500/50 bg-purple-500/10 text-purple-400 animate-pulse' 
                        : 'border-slate-800 text-slate-600'
                    }`}>
                      {isDone ? <Check className="w-2.5 h-2.5" /> : <span className="text-[8px]">{idx+1}</span>}
                    </div>
                    <span className="truncate">{stage}</span>
                  </div>
                );
              })}
            </Card>
          </div>
        )}

        {/* Empty Dashboard State (Landing Page) */}
        {!isLoading && !activeReport && (
          <HeroSection 
            onSearch={(q, d, comp, date, filters) => {
              startResearch(q, d, comp, date, filters);
            }} 
          />
        )}

        {/* Report Dashboard State */}
        {!isLoading && activeReport && (
          <div className="space-y-6 flex-1 flex flex-col">
            
            {/* Top Back-To-Search and Exporter Control bar */}
            <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 border-b border-white/5 pb-5 no-print">
              <button 
                onClick={() => setActiveReport(null as any)}
                className="flex items-center gap-2 text-slate-400 hover:text-white transition-colors text-xs font-semibold self-start"
              >
                <ArrowLeft className="w-4 h-4" /> Back to Research Desk
              </button>

              <div className="flex flex-wrap items-center gap-2">
                {/* Change detection compare button */}
                {diffData && (
                  <button
                    onClick={() => setShowDiffModal(true)}
                    className="flex items-center gap-1.5 px-3 py-1.5 rounded-xl bg-pink-500/15 border border-pink-500/30 text-pink-300 hover:text-pink-100 text-xs font-bold transition-all"
                  >
                    <GitCompare className="w-3.5 h-3.5" /> Track Variations
                  </button>
                )}

                <button
                  onClick={handleShare}
                  className="px-3 py-1.5 bg-slate-900 border border-white/5 hover:border-purple-500/20 text-slate-300 hover:text-purple-300 text-xs font-semibold rounded-xl transition-all"
                >
                  {copyStatus ? 'Link Copied!' : 'Share'}
                </button>

                {/* Exporter selector */}
                <div className="relative group">
                  <button className="flex items-center gap-1.5 px-3 py-1.5 bg-purple-500/10 border border-purple-500/30 text-purple-300 hover:text-purple-100 text-xs font-bold rounded-xl transition-all">
                    <Download className="w-3.5 h-3.5" /> Export Data
                  </button>
                  {/* Dropdown overlay */}
                  <div className="absolute right-0 mt-1.5 w-40 bg-slate-900 border border-white/10 rounded-xl shadow-2xl p-2 hidden group-hover:block hover:block space-y-1 z-50 animate-fade-in">
                    <button 
                      onClick={triggerPrintPDF} 
                      className="w-full text-left px-3 py-2 text-[11px] text-slate-300 hover:bg-white/5 rounded-lg flex items-center gap-2 font-medium"
                    >
                      <FileText className="w-3.5 h-3.5 text-purple-400" /> Export PDF
                    </button>
                    <button 
                      onClick={() => exportToMarkdown(activeReport)} 
                      className="w-full text-left px-3 py-2 text-[11px] text-slate-300 hover:bg-white/5 rounded-lg flex items-center gap-2 font-medium"
                    >
                      <Code className="w-3.5 h-3.5 text-cyan-400" /> Markdown
                    </button>
                    <button 
                      onClick={() => exportToWord(activeReport)} 
                      className="w-full text-left px-3 py-2 text-[11px] text-slate-300 hover:bg-white/5 rounded-lg flex items-center gap-2 font-medium"
                    >
                      <FileText className="w-3.5 h-3.5 text-blue-400" /> MS Word (.doc)
                    </button>
                    <button 
                      onClick={() => exportToJSON(activeReport)} 
                      className="w-full text-left px-3 py-2 text-[11px] text-slate-300 hover:bg-white/5 rounded-lg flex items-center gap-2 font-medium"
                    >
                      <Database className="w-3.5 h-3.5 text-pink-400" /> Raw JSON
                    </button>
                  </div>
                </div>
              </div>
            </div>

            {/* Print Header (Only visible when printing to PDF) */}
            <div className="hidden print-show space-y-4 mb-6">
              <h1 className="text-3xl font-extrabold">{activeReport.title}</h1>
              <p className="text-sm text-slate-500">NEXUS AI OS Intelligence Report | Key: {activeReport.id} | Generated: {new Date(activeReport.timestamp).toLocaleString()}</p>
            </div>

            {/* 3. SIDE-BY-SIDE DASHBOARD LAYOUT */}
            <div className="grid grid-cols-1 xl:grid-cols-4 gap-6 items-start">
              
              {/* Left Column: Tab Navigator and Tab Content */}
              <div className="xl:col-span-3 space-y-6">
                
                {/* Horizontal Tab Trigger Row */}
                <div className="flex flex-wrap gap-1.5 p-1 bg-slate-950/40 border border-white/5 rounded-2xl no-print">
                  <button
                    onClick={() => setActiveTab('summary')}
                    className={`px-4 py-2 rounded-xl text-xs font-bold transition-all ${
                      activeTab === 'summary' ? 'bg-purple-500/10 text-purple-300 border border-purple-500/20' : 'text-slate-400 hover:text-slate-200'
                    }`}
                  >
                    Briefing
                  </button>

                  <button
                    onClick={() => setActiveTab('insights')}
                    className={`px-4 py-2 rounded-xl text-xs font-bold transition-all ${
                      activeTab === 'insights' ? 'bg-purple-500/10 text-purple-300 border border-purple-500/20' : 'text-slate-400 hover:text-slate-200'
                    }`}
                  >
                    Insights
                  </button>

                  {activeReport.competitorComparison && (
                    <button
                      onClick={() => setActiveTab('comparison')}
                      className={`px-4 py-2 rounded-xl text-xs font-bold transition-all flex items-center gap-1.5 ${
                        activeTab === 'comparison' ? 'bg-pink-500/10 text-pink-300 border border-pink-500/20' : 'text-slate-400 hover:text-slate-200'
                      }`}
                    >
                      <Landmark className="w-3.5 h-3.5" /> Comparisons
                    </button>
                  )}

                  <button
                    onClick={() => setActiveTab('technical')}
                    className={`px-4 py-2 rounded-xl text-xs font-bold transition-all ${
                      activeTab === 'technical' ? 'bg-purple-500/10 text-purple-300 border border-purple-500/20' : 'text-slate-400 hover:text-slate-200'
                    }`}
                  >
                    Deep Dive
                  </button>

                  <button
                    onClick={() => setActiveTab('graph')}
                    className={`px-4 py-2 rounded-xl text-xs font-bold transition-all ${
                      activeTab === 'graph' ? 'bg-purple-500/10 text-purple-300 border border-purple-500/20' : 'text-slate-400 hover:text-slate-200'
                    }`}
                  >
                    Knowledge Graph
                  </button>

                  <button
                    onClick={() => setActiveTab('risks')}
                    className={`px-4 py-2 rounded-xl text-xs font-bold transition-all ${
                      activeTab === 'risks' ? 'bg-purple-500/10 text-purple-300 border border-purple-500/20' : 'text-slate-400 hover:text-slate-200'
                    }`}
                  >
                    Contradictions & Risks
                  </button>

                  <button
                    onClick={() => setActiveTab('timeline')}
                    className={`px-4 py-2 rounded-xl text-xs font-bold transition-all ${
                      activeTab === 'timeline' ? 'bg-purple-500/10 text-purple-300 border border-purple-500/20' : 'text-slate-400 hover:text-slate-200'
                    }`}
                  >
                    Timeline & Forecasts
                  </button>

                  <button
                    onClick={() => setActiveTab('sources')}
                    className={`px-4 py-2 rounded-xl text-xs font-bold transition-all ${
                      activeTab === 'sources' ? 'bg-purple-500/10 text-purple-300 border border-purple-500/20' : 'text-slate-400 hover:text-slate-200'
                    }`}
                  >
                    Sources ({activeReport.sources.length})
                  </button>
                </div>

                {/* Tab Content Rendering */}
                <div className="bg-slate-900/10 border border-white/5 rounded-3xl p-6 backdrop-blur-sm print:border-none print:p-0">
                  {activeTab === 'summary' && <ExecutiveSummary report={activeReport} />}
                  {activeTab === 'insights' && <KeyInsights report={activeReport} />}
                  {activeTab === 'technical' && (
                    <div className="space-y-10">
                      <TechnicalDeepDive report={activeReport} />
                      <div className="border-t border-white/5 pt-8 print-page-break">
                        <TrendAnalysis report={activeReport} />
                      </div>
                    </div>
                  )}
                  {activeTab === 'graph' && <KnowledgeGraph report={activeReport} />}
                  {activeTab === 'risks' && <OpportunitiesRisks report={activeReport} />}
                  
                  {activeTab === 'sources' && (
                    <div className="space-y-10">
                      <SourceExplorer report={activeReport} />
                      <div className="border-t border-white/5 pt-8 print-page-break">
                        <ImageGallery report={activeReport} />
                      </div>
                    </div>
                  )}

                  {activeTab === 'timeline' && (
                    <div className="space-y-10">
                      {/* Timeline of developments */}
                      <div className="space-y-6">
                        <div className="flex flex-col gap-1">
                          <h2 className="text-2xl font-bold tracking-tight text-white">Development Timeline</h2>
                          <p className="text-slate-400 text-sm">Chronological outline of publications and forecasted deployment benchmarks.</p>
                        </div>
                        
                        <div className="relative pl-6 border-l border-purple-500/30 space-y-8">
                          {activeReport.timeline.map((event, i) => (
                            <div key={i} className="relative">
                              {/* Indicator node */}
                              <div className="absolute -left-[31px] top-1.5 w-4.5 h-4.5 rounded-full border border-purple-500 bg-slate-950 flex items-center justify-center">
                                <span className="w-1.5 h-1.5 rounded-full bg-purple-400" />
                              </div>
                              
                              <div className="space-y-1">
                                <div className="text-[10px] uppercase font-bold text-cyan-400 flex items-center gap-2">
                                  <span>{event.period}</span>
                                  {event.date && <span className="text-slate-500">({event.date})</span>}
                                </div>
                                <h4 className="text-sm font-bold text-slate-200">{event.title}</h4>
                                <p className="text-slate-400 text-xs leading-relaxed max-w-2xl">{event.description}</p>
                              </div>
                            </div>
                          ))}
                        </div>
                      </div>

                      {/* Forecasting engine outlook cards */}
                      <div className="border-t border-white/5 pt-8 space-y-6 print-page-break">
                        <div className="flex flex-col gap-1">
                          <h3 className="text-xl font-bold text-white">Strategic Horizon Forecasts</h3>
                          <span className="text-xs text-slate-500">Algorithmic predictions on standard adoption vectors.</span>
                        </div>

                        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                          {activeReport.forecasts.map((forecast, idx) => (
                            <Card key={idx} className="border border-white/5 bg-slate-950/20 p-5 space-y-3">
                              <div className="flex items-center justify-between">
                                <span className="text-xs font-mono font-bold text-purple-400">{forecast.period} Horizon</span>
                                <span className="text-[10px] px-2 py-0.5 rounded-full bg-cyan-500/10 text-cyan-300 font-semibold border border-cyan-500/20">
                                  {forecast.confidenceEstimate}% Probability
                                </span>
                              </div>
                              <p className="text-slate-300 text-xs leading-relaxed">{forecast.outlook}</p>
                            </Card>
                          ))}
                        </div>
                      </div>
                    </div>
                  )}

                  {activeTab === 'comparison' && activeReport.competitorComparison && (
                    <div className="space-y-6">
                      <div className="flex items-center gap-2">
                        <div className="p-2 bg-pink-500/10 text-pink-400 rounded-lg border border-pink-500/20">
                          <Landmark className="w-5 h-5" />
                        </div>
                        <h2 className="text-2xl font-bold tracking-tight text-white">Competitive Intelligence Engine</h2>
                      </div>
                      <p className="text-slate-400 text-sm">Side-by-side analysis of funding reserves, baseline products, ongoing research paths, and partnerships.</p>

                      <div className="grid grid-cols-1 md:grid-cols-2 gap-6 pt-4">
                        {/* Competitor A */}
                        <Card className="border border-purple-500/20 bg-slate-950/50 p-6 space-y-4">
                          <div className="flex items-center justify-between border-b border-white/5 pb-3">
                            <h3 className="text-lg font-bold text-white">{activeReport.competitorComparison.competitorA}</h3>
                            <span className="text-xs px-2.5 py-0.5 rounded-full bg-purple-500/10 text-purple-300 border border-purple-500/20 font-bold">
                              {activeReport.competitorComparison.fundingA || 'Funding Unknown'}
                            </span>
                          </div>
                          
                          <div className="space-y-4 text-xs">
                            <div>
                              <strong className="text-slate-400 block mb-1">Market Products</strong>
                              <ul className="list-disc pl-4 space-y-1 text-slate-300">
                                {activeReport.competitorComparison.productsA.map((p, i) => <li key={i}>{p}</li>)}
                              </ul>
                            </div>
                            <div>
                              <strong className="text-slate-400 block mb-1">Active Research Vector</strong>
                              <p className="text-slate-300 leading-relaxed">{activeReport.competitorComparison.researchA}</p>
                            </div>
                            <div>
                              <strong className="text-slate-400 block mb-1">Strategic Partnerships</strong>
                              <p className="text-slate-300">{activeReport.competitorComparison.partnershipsA.join(', ')}</p>
                            </div>
                            <div>
                              <strong className="text-slate-400 block mb-1">Market Position</strong>
                              <p className="text-slate-300">{activeReport.competitorComparison.marketPositionA}</p>
                            </div>
                          </div>
                        </Card>

                        {/* Competitor B */}
                        <Card className="border border-cyan-500/20 bg-slate-950/50 p-6 space-y-4">
                          <div className="flex items-center justify-between border-b border-white/5 pb-3">
                            <h3 className="text-lg font-bold text-white">{activeReport.competitorComparison.competitorB}</h3>
                            <span className="text-xs px-2.5 py-0.5 rounded-full bg-cyan-500/10 text-cyan-300 border border-cyan-500/20 font-bold">
                              {activeReport.competitorComparison.fundingB || 'Funding Unknown'}
                            </span>
                          </div>
                          
                          <div className="space-y-4 text-xs">
                            <div>
                              <strong className="text-slate-400 block mb-1">Market Products</strong>
                              <ul className="list-disc pl-4 space-y-1 text-slate-300">
                                {activeReport.competitorComparison.productsB.map((p, i) => <li key={i}>{p}</li>)}
                              </ul>
                            </div>
                            <div>
                              <strong className="text-slate-400 block mb-1">Active Research Vector</strong>
                              <p className="text-slate-300 leading-relaxed">{activeReport.competitorComparison.researchB}</p>
                            </div>
                            <div>
                              <strong className="text-slate-400 block mb-1">Strategic Partnerships</strong>
                              <p className="text-slate-300">{activeReport.competitorComparison.partnershipsB.join(', ')}</p>
                            </div>
                            <div>
                              <strong className="text-slate-400 block mb-1">Market Position</strong>
                              <p className="text-slate-300">{activeReport.competitorComparison.marketPositionB}</p>
                            </div>
                          </div>
                        </Card>
                      </div>

                      {/* Merged Summary */}
                      <Card className="border border-white/5 bg-slate-950/30 p-5 mt-4">
                        <strong className="text-xs text-slate-400 uppercase tracking-wider block mb-2">Synthesis Summary</strong>
                        <p className="text-xs text-slate-300 leading-relaxed italic">
                          "{activeReport.competitorComparison.sideBySideSummary}"
                        </p>
                      </Card>
                    </div>
                  )}
                </div>

                {/* Print Version of all tabs (Ensures that when printing to PDF, ALL sections print automatically!) */}
                <div className="hidden print-show space-y-12">
                  <div className="print-page-break">
                    <ExecutiveSummary report={activeReport} />
                  </div>
                  <div className="print-page-break">
                    <KeyInsights report={activeReport} />
                  </div>
                  <div className="print-page-break">
                    <TechnicalDeepDive report={activeReport} />
                  </div>
                  <div className="print-page-break">
                    <TrendAnalysis report={activeReport} />
                  </div>
                  <div className="print-page-break">
                    <OpportunitiesRisks report={activeReport} />
                  </div>
                  <div className="print-page-break">
                    <SourceExplorer report={activeReport} />
                  </div>
                </div>

              </div>

              {/* Right Column: Persistent Copilot Chat panel */}
              <div className="xl:col-span-1 no-print">
                <ResearchCopilot />
              </div>
            </div>

          </div>
        )}
      </main>

      {/* 4. DOCK LEGEND AND FOOTER */}
      <footer className="py-8 text-center text-xs text-slate-600 border-t border-white/5 relative z-10 no-print mt-auto">
        <span>Powered by Context.dev Scraping Nodes & Google Gemini 2.5 Multi-Agent Engine.</span>
      </footer>

      {/* 5. DIFFERENCE CHECKER OVERLAY MODAL */}
      {showDiffModal && diffData && activeReport && (
        <div 
          className="fixed inset-0 bg-slate-950/80 backdrop-blur-md z-50 flex items-center justify-center p-4 animate-fade-in no-print"
          onClick={() => setShowDiffModal(false)}
        >
          <div 
            className="bg-slate-900 border border-white/10 rounded-3xl p-6 max-w-xl w-full space-y-6 shadow-2xl relative"
            onClick={(e) => e.stopPropagation()}
          >
            <div className="flex items-center gap-2">
              <GitCompare className="w-5 h-5 text-pink-400" />
              <h3 className="text-lg font-bold text-slate-100">Historical Change Detection</h3>
            </div>
            
            <p className="text-xs text-slate-400">
              Comparing latest research updates with previous logs of <strong className="text-slate-200">"{activeReport.query}"</strong>.
            </p>

            <div className="space-y-4 max-h-[350px] overflow-y-auto pr-1 text-xs">
              
              {/* Added */}
              {diffData.addedFindings.length > 0 && (
                <div className="space-y-2">
                  <strong className="text-emerald-400 uppercase tracking-wide text-[10px] block">New Insights Added</strong>
                  <ul className="list-disc pl-4 space-y-1.5 text-slate-300">
                    {diffData.addedFindings.map((f, i) => <li key={i}>{f}</li>)}
                  </ul>
                </div>
              )}

              {/* New Trends */}
              {diffData.newTrends.length > 0 && (
                <div className="space-y-2">
                  <strong className="text-cyan-400 uppercase tracking-wide text-[10px] block">New Trends Mapped</strong>
                  <ul className="list-disc pl-4 space-y-1.5 text-slate-300">
                    {diffData.newTrends.map((t, i) => <li key={i}>{t}</li>)}
                  </ul>
                </div>
              )}

              {/* Stat updates */}
              {diffData.updatedStatistics.length > 0 && (
                <div className="space-y-2">
                  <strong className="text-purple-400 uppercase tracking-wide text-[10px] block">Statistical Updates</strong>
                  <ul className="list-disc pl-4 space-y-1.5 text-slate-300">
                    {diffData.updatedStatistics.map((s, i) => <li key={i}>{s}</li>)}
                  </ul>
                </div>
              )}

              {diffData.addedFindings.length === 0 && diffData.newTrends.length === 0 && diffData.updatedStatistics.length === 0 && (
                <div className="text-center py-6 text-slate-500">No core metrics or insights have diverged since your last query sequence.</div>
              )}
            </div>

            <div className="pt-4 border-t border-white/5 flex justify-end">
              <button 
                onClick={() => setShowDiffModal(false)}
                className="px-4 py-2 bg-purple-500 hover:bg-purple-600 text-white font-bold text-xs rounded-xl"
              >
                Close Log
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
